version: "3.5"

volumes:
       

        wordpress:
                driver: local
                name: wordpress
                driver_opts:
                        type: none
                        o: bind
                        device: /home/bprovolo/data/wordpress

        db:
                driver: local
                name: db
                driver_opts:
                        type: none
                        o: bind
                        device: /home/bprovolo/data/db

networks:
        inception:
                name: inception
                driver: bridge

services:
  nginx:
        image: nginx
        volumes:
        - wordpress:/var/www/html
        container_name: nginx
        build:  ./requirements/nginx
        ports: 
                - "443:443"
        user: root
        env_file: .env
        restart: always
        networks:
                - inception
        depends_on:
                - wordpress
  wordpress:
        image: wordpress
        env_file: .env
        depends_on:
                  - mariadb
        container_name: wordpress
        restart: always
        build: ./requirements/wordpress
        user: root
        volumes:
                  - wordpress:/var/www/html
        networks:
                  - inception

  mariadb:
        image: mariadb
        env_file: .env
        build: ./requirements/mariadb/
        restart: always
        volumes: 
                - db:/var/lib/mysql
        user: root
        networks: 
                - inception
        container_name: mariadb
