version: "3.5"

networks:
        inception:
                driver: bridge

services:
  nginx:
        container_name: nginx
        build:  ./requirements/nginx
        ports: 
                - "443:443"
        volumes:
                - wordpress:/var/www/html/wordpress
        networks:
                - inception
        depends_on:
                - wordpress
  wordpress:
          container_name: wordpress
          build: ./requirements/wordpress
          volumes:
                  - wordpress:/var/www/html/wordpress
          networks:
                  - inception
          depends_on:
                  - mariadb
  mariadb:
          container_name: mariadb
          env_file: .env
          build: ./requirements/mariadb
          restart: always
          volumes: 
                - db:/var/lib/mysql
          networks: 
                - inception
volumes:
        db:
                name: db
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        # device: /home/bprovolo/data/db

        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        # device: /home/bprovolo/data/wordpress

