version: "3.9"

networks:
        inception:
                driver: bridge

services:
  nginx:
        container_name: nginx
        build:  ./nginx
        ports: 
                -"443:443"
        volumes:

volumes:
        DB:
        WordPress:
